# Linear Regression in Julia

In [2]:
using Statistics
using LinearAlgebra

In [3]:
f(x) = 3+x^3;

In [6]:
y = range(-2, stop=2, length = 200);
X = [f(x) for x in y_test];
y = [a for a in y];

In [7]:
X = [ones(size(X)[1]) X];

In [106]:
theta = rand(size(X)[2],1);

In [93]:
theta

2×1 Matrix{Float64}:
 0.5101898633389419
 0.7418039744145006

In [43]:
m = size(X)[1]

200

In [44]:
transpose(theta)*theta

1×1 Matrix{Float64}:
 NaN

In [45]:
E(t, g) = (norm(X*t - y, 2)^2 + g*norm(t)^2) /2m;

In [67]:
grad_E(t, g) = (t * g + transpose(X) * (X*t-y))/m;

In [55]:
 (transpose(X) * (X*theta - y))

2×1 Matrix{Float64}:
 NaN
 NaN

In [69]:
gamma = 1;

In [91]:
alpha = 0.1

0.1

In [88]:
theta-=alpha*grad_E(theta, gamma)

2×1 Matrix{Float64}:
 -436239.0760116183
      -2.60616254881659e6

In [112]:
while norm(grad_E(theta, gamma))>10^(-5)
    theta -= alpha*grad_E(theta, gamma)
end

In [108]:
function kfold(data, folds)

2×1 Matrix{Float64}:
 -1.0289925409000928
  0.34471578229589805

In [114]:
println("gamma = ", gamma, ", error = ", E(theta, gamma))

gamma = 1, error = 0.11069294391847401
